### ISSUE TITLE
Installation missing a step?

### ISSUE THREAD

**Issue by bshaffer** [JustinBeckwith/flem#1]
```
# me:
$ npm install -g flem
# Installed!! Hooray!
# me:
$ flem 
-bash: flem: command not found!!
# me: ??
# me:
$ /usr/local/Cellar/node/4.1.1/libexec/npm/lib/node_modules/flem/bin/cli.js
# ... waits a really long time without anything happening
```

**Comment by bshaffer** [comment]
I just figured out the wait is happening because there isn't an `app.yaml` in my cwd.

```
# me:
$ /usr/local/Cellar/node/4.1.1/libexec/npm/lib/node_modules/flem/bin/cli.js /path/to/project/with/appyaml/
# It works as expected!
```

**Comment by JustinBeckwith** [comment]
I added 21cca53  to do a better job of surfacing the "no app.yaml" error, and 0a32cc9 to make sure we test on node v4.  I'm not sure why the linking step doesn't seem to be working.  Let me try this on a 'not my machine'.

**Comment by JustinBeckwith** [comment]
Also added 6f8a376 to help with the errors.  @bshaffer - can you try doing the `npm install -g flem` again?  If that doesn't work - can you try another package, say `npm install -g nodemon` to see if that works?  Hard to tell if this is an installation problem or a library problem.  Thank you!

**Comment by JustinBeckwith** [comment]
Pretty sure this is in good order, feel free to re-open if you still run into trouble.
