### ISSUE TITLE
Bring in select environment variables

### ISSUE THREAD

**Issue by bshaffer** [JustinBeckwith/flem#2]
Environment variables expected in the app engine flexible runtime, such as `GCLOUD_PROJECT`, should be plucked from the local scope when building the docker container. For example:

```
$ export GCLOUD_PROJECT=myproject
$ flem 
# the resulting container should have `GCLOUD_PROJECT` set to `myproject`
```

**Comment by JustinBeckwith** [comment]
This is in the latest build!
